name: "Publish chart to gcp"
description: "Build index and upload chart to gcp"
runs:
  using: "composite"
  steps:
    - name: Load Secrets from Vault
      if: github.event_name == 'push' && contains(github.ref, 'tags/') # Only run on tags
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/google-auth/rancher/credentials token | GOOGLE_AUTH ;
    - name: Authenticate with Google Cloud
      if: github.event_name == 'push' && contains(github.ref, 'tags/') # Only run on tags
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.GOOGLE_AUTH }}
    - name: Upload
      if: github.event_name == 'push' && contains(github.ref, 'tags/') # Only run on tags
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        destination: releases.rancher.com/server-charts
        path: ./bin/chart
        parent: false
        process_gcloudignore: false
        predefinedAcl: publicRead
        headers: |-
          cache-control: public,no-cache,proxy-revalidate

