name: "Fetch registry info"
description: "Fetch the registry url, username and password"
inputs:
  registry_type:
    description: "registry type, 'dockerio' or 'staging'"
    required: true
    type: choice
    options:
      - "dockerio"
      - "staging"
outputs:
  url:
    description: "registry url"
    value: ${{ steps.secrets.outputs.url }}
  username:
    description: "registry username"
    value: ${{ steps.secrets.outputs.username }}
  password:
    description: "registry password"
    value: ${{ steps.secrets.outputs.password }}
runs:
  using: "composite"
  steps:
    - name: Load Docker Hub Secrets from Vault
      if: inputs.registry_type == 'dockerio'
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | REGISTRY_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | REGISTRY_PASSWORD
    - name: Export Docker Hub URL
      if: inputs.registry_type == 'dockerio'
      shell: bash
      run: echo "REGISTRY=docker.io" >> $GITHUB_ENV
    - name: Load Staging Secrets from Vault
      if: inputs.registry_type == 'staging'
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/stage-registry-username/credentials token | REGISTRY_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/stage-registry-password/credentials token | REGISTRY_PASSWORD
    - name: Export Staging URL
      if: inputs.registry_type == 'staging'
      shell: bash
      run: echo "REGISTRY=stgregistry.suse.com" >> $GITHUB_ENV
    - name: Output secrets
      id: secrets
      shell: bash
      run: |
        echo "url=${{ env.REGISTRY }}" >> $GITHUB_OUTPUT
        echo "username=${{ env.REGISTRY_USERNAME }}" >> $GITHUB_OUTPUT
        echo "password=${{ env.REGISTRY_PASSWORD }}" >> $GITHUB_OUTPUT
