name: "Fetch registry info"
description: "Fetch the registry url, username and password"
inputs:
  registry_type:
    description: "registry type, 'dockerio' or 'staging'"
    required: true
    type: choice
    options:
      - "dockerio"
      - "staging"
outputs:
  url:
    description: "registry url"
    value: ${{ steps.secrets.outputs.url }}
  username:
    description: "registry username"
    value: ${{ steps.secrets.outputs.username }}
  password:
    description: "registry password"
    value: ${{ steps.secrets.outputs.password }}
runs:
  using: "composite"
  steps:
    - name: Get registry info
      id: registry
      shell: bash
      run: |
        case ${{ inputs.registry_type }} in
          dockerio)
            echo "url='docker.io'" >> $GITHUB_OUTPUT

            echo "USERNAME_SECRET_PATH=\"secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username\"" >> $GITHUB_ENV
            echo "PASSWORD_SECRET_PATH=\"secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password\"" >> $GITHUB_ENV
            ;;
          staging)
            echo "url='stgregistry.suse.com'" >> $GITHUB_OUTPUT

            echo "USERNAME_SECRET_PATH=\"secret/data/github/repo/${{ github.repository }}/stage-registry-username/credentials token\"" >> $GITHUB_ENV
            echo "PASSWORD_SECRET_PATH\"=secret/data/github/repo/${{ github.repository }}/stage-registry-password/credentials token\"" >> $GITHUB_ENV
            ;;
          *)
            echo "error: invalid value" >&2
            exit 1
            ;;
        esac
    - name: Load Secrets from Vault
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          ${{ env.USERNAME_SECRET_PATH }} | REGISTRY_USERNAME ;
          ${{ env.USERNAME_PASSWORD_PATH }} | REGISTRY_PASSWORD
    - name: Output secrets
      id: secrets
      shell: bash
      run: |
        echo "url=${{ steps.registry.outputs.url }}" >> $GITHUB_OUTPUT
        echo "username=${{ env.REGISTRY_USERNAME }}" >> $GITHUB_OUTPUT
        echo "password=${{ env.REGISTRY_PASSWORD }}" >> $GITHUB_OUTPUT
