name: Build agent windows
on:
  workflow_call:
    inputs:
      registry:
        type: string
        description: "docker registry to push the image to"
        required: true
      registry-username-path:
        type: string
        description: "registry username secret path"
        required: true
      registry-password-path:
        type: string
        description: "registry password secret path"
        required: true
jobs:
  build-agent-windows:
    strategy:
      matrix:
        os: [windows]
        version: [2019, 2022]
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    permissions:
      contents: read
      id-token: write
    env:
      REGISTRY: ${{ inputs.registry }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment Variables
        uses: ./.github/actions/setup-tag-env
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            ${{ inputs.registry-username-path }} | REGISTRY_USERNAME ;
            ${{ inputs.registry-password-path }} | REGISTRY_PASSWORD ;
      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.REGISTRY }}
      - name: Build Windows Server Image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-windows-${{ matrix.version }} --build-arg VERSION=${{ env.TAG }} --build-arg SERVERCORE_VERSION=ltsc${{ matrix.version }} -f package/windows/Dockerfile.agent .
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-windows-${{ matrix.version }}
        shell: bash
