name: Merge server manifest
on:
  workflow_call:
    inputs:
      registry:
        type: string
        description: "docker registry to push the image to"
        required: true
      registry-username-path:
        type: string
        description: "registry username secret path"
        required: true
      registry-password-path:
        type: string
        description: "registry password secret path"
        required: true
jobs:
  merge-server-manifest:
    runs-on: runs-on,runner=2cpu-linux-x64,image=ubuntu22-full-x64,run-id=${{ github.run_id }}
    permissions:
      contents: read
      id-token: write
    env:
      REGISTRY: "stgregistry.suse.com"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment Variables
        uses: ./.github/actions/setup-tag-env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/stage-registry-username/credentials token | STAGE_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/stage-registry-password/credentials token | STAGE_REGISTRY_PASSWORD ;
      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.STAGE_REGISTRY_USERNAME }}
          password: ${{ env.STAGE_REGISTRY_PASSWORD }}
          registry: ${{ env.REGISTRY }}
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher:${{ env.TAG }} ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher:${{ env.TAG }}-amd64 ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher:${{ env.TAG }}-arm64
      - name: Create head manifest list and push
        run: |
          if [[ "${{ github.ref_name }}" == release/v* ]] || [[ "${{ github.ref_name }}" == "main" ]]; then
            docker buildx imagetools create -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher:${{ env.HEAD_TAG }} ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher:${{ env.TAG }}-amd64 ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher:${{ env.TAG }}-arm64
          fi
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ github.repository_owner }}/rancher:${{ env.TAG }}
