name: Merge agent manifest
on:
  workflow_call:
    inputs:
      registry_type:
        description: "docker registry to push the image to"
        required: true
        type: string
jobs:
  merge-agent-manifest:
    runs-on: runs-on,runner=2cpu-linux-x64,image=ubuntu22-full-x64,run-id=${{ github.run_id }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment Variables
        uses: ./.github/actions/setup-tag-env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get Registry Info
        id: registry_info
        uses: ./.github/actions/registry-info
        with:
          registry_type: ${{ inputs.registry_type }}
      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.registry_info.outputs.url }}
          username: ${{ steps.registry_info.outputs.username }}
          password: ${{ steps.registry_info.outputs.password }}
      - name: Create manifest list and push
        run: |
          # docker manifest is used with windows images to maintain os.version in the manifest
          docker manifest create ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }} \
            ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-windows-2019 \
            ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-windows-2022

          docker manifest push ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}

          # docker buildx imagetools create pushes to the registry by default, which is not the same behavior as docker manifest create
          docker buildx imagetools create -t ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }} \
            --append ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-amd64 \
            --append ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-arm64 

          if [[ "${{ github.ref_name }}" == release/v* ]] || [[ "${{ github.ref_name }}" == "main" ]]; then
            docker manifest create ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.HEAD_TAG }} \
              ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-windows-2019 \
              ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-windows-2022
            docker manifest push ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.HEAD_TAG }}

            docker buildx imagetools create -t ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.HEAD_TAG }} \
              --append ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-amd64 \
              --append ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-arm64 
          fi
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}

