name: Push Server and agent images
on:
  workflow_call:
    inputs:
      registry_type:
        description: "docker registry to push the image to"
        required: true
        type: choice
        options:
          - "dockerio"
          - "staging"
jobs:
  push-images:
    strategy:
      matrix:
        os: [linux]
        arch: [x64, arm64]
    runs-on: runs-on,runner=2cpu-${{ matrix.os }}-${{ matrix.arch }},image=ubuntu22-full-${{ matrix.arch }},run-id=${{ github.run_id }}
    permissions:
      contents: read
      id-token: write
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - name: Environment variables
        shell: bash
        run: |
          if [[ "$ARCH" == "x64" ]]; then
            echo "ARCH=amd64" >> $GITHUB_ENV
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download rancher image
        uses: actions/download-artifact@v4
        with:
          pattern: "*-${{ matrix.os }}-${{ env.ARCH }}"
          path: /tmp
          merge-multiple: true
      - name: Get Registry Info
        id: registry_info
        uses: ./.github/actions/registry-info
        with:
          registry_type: ${{ inputs.registry_type }}
      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.registry_info.outputs.url }}
          username: ${{ steps.registry_info.outputs.username }}
          password: ${{ steps.registry_info.outputs.password }}
      - name: Push server image
        env:
          REGISTRY: ${{ stesp.registry_info.outputs.url }}
        run: |
          image_id=$(docker load --input /tmp/rancher-${{ matrix.os }}-${{ env.ARCH }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
          if [ -z "$image_id" ]; then
            echo "Error: Failed to load image from tarball!"
            exit 1
          fi
          docker tag "$image_id" ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher:${{ env.TAG }}-${{ env.ARCH }}
          docker push ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher:${{ env.TAG }}-${{ env.ARCH }}
      - name: Push agent image
        run: |
          image_agent_id=$(docker load --input /tmp/rancher-agent-${{ matrix.os }}-${{ env.ARCH }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
          if [ -z "$image_agent_id" ]; then
            echo "Error: Failed to load image from tarball!"
            exit 1
          fi
          docker tag "$image_agent_id" ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-${{ env.ARCH }}
          docker push ${{ steps.registry_info.outputs.url }}/${{ github.repository_owner }}/rancher-agent:${{ env.TAG }}-${{ env.ARCH }}
